# Generated by Django 3.2.17 on 2023-02-21 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('accountNum', models.AutoField(primary_key=True, serialize=False)),
                ('paymentServiceId', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('balance', models.FloatField()),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundPayment',
            fields=[
                ('outboundPaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('fromPaymentServiceId', models.IntegerField()),
                ('toAccountNum', models.IntegerField()),
                ('toPaymentServiceId', models.IntegerField()),
                ('amount', models.FloatField()),
                ('allowed', models.DateTimeField(default=None)),
                ('transferred', models.BooleanField(default=False)),
                ('fromAccountNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
