# Generated by Django 3.2.17 on 2023-02-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayBudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundpayment',
            name='allowed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
